# Generated by Django 4.0.4 on 2022-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PredictionsID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('FileName', models.CharField(max_length=200)),
                ('ImageDate', models.CharField(max_length=200)),
                ('PredictedPlant', models.CharField(max_length=200)),
                ('AllPredictedPlants', models.CharField(max_length=200)),
                ('Score', models.CharField(max_length=20)),
                ('DateAdded', models.CharField(max_length=200)),
                ('Comments', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
