# Generated by Django 4.0.4 on 2022-07-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_predictionsmodel_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='AllPredictedPlants',
            new_name='allpredictedplants',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='DateAdded',
            new_name='dateadded',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='FileName',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='ImageDate',
            new_name='imagedate',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='PredictedPlant',
            new_name='predictedplant',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='PredictionsID',
            new_name='predictionsid',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='Score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='predictionsmodel',
            old_name='Surname',
            new_name='surname',
        ),
    ]
