# Generated by Django 4.0.6 on 2022-09-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_allpredictedplants_predictionsmodel_allpredictedplants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='identificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificationsid', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('identifiedplant', models.CharField(max_length=200)),
                ('allidentifiedplants', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'identifications',
            },
        ),
        migrations.CreateModel(
            name='imageinformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificationsid', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('imagedate', models.CharField(max_length=200)),
                ('dateadded', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
            options={
                'db_table': 'imageinformation',
            },
        ),
        migrations.CreateModel(
            name='userinformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificationsid', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'userinformation',
            },
        ),
        migrations.AddField(
            model_name='predictionsmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=25, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionsmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=25, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionsmodel',
            name='dateadded',
            field=models.DateTimeField(),
        ),
    ]
