# Generated by Django 4.0.6 on 2023-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_identificationsmodel_imageinformationmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='predictionsModel',
        ),
        migrations.AddField(
            model_name='identificationsmodel',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='identificationsmodel',
            name='allidentifiedplants',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='identificationsmodel',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='identificationsmodel',
            name='identifiedplant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='identificationsmodel',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='imageinformationmodel',
            name='dateadded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imageinformationmodel',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imageinformationmodel',
            name='imagedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imageinformationmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=25, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='imageinformationmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinformationmodel',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinformationmodel',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinformationmodel',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformationmodel',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
