# Generated by Django 4.0 on 2023-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_identificationsmodel_allidentifiedplants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
