version: "3.7"
services:
 
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    expose:
      - 5432
    ports:
        - "5432:5432"
    volumes:
        - ./db/data:/var/lib/pgsql/data/
        - ./db/init/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5
  
  backend:
    container_name: backend
    image: backend:latest
    restart: always
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: "service_healthy"
  
  frontend:
    container_name: frontend
    image: frontend:latest
    restart: always
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: npm start
  

     

  