"""
Django settings for PlantFinder project.
Generated by 'django-admin startproject' using Django 4.0.4.
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG')

ALLOWED_HOSTS = os.environ.get('HOST_NAMES').split()

# Application definition

INSTALLED_APPS = [
    'sslserver',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
	'corsheaders',
 	'rest_framework',
     
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'PlantFinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'PlantFinder.wsgi.application'
ASGI_APPLICATION = 'PlantFinder.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# 


isAWS=os.environ.get('IS_AWS')
isDocker=os.environ.get('IS_DOCKER')
isLocal=os.environ.get('IS_LOCAL')

ENGINE=os.environ.get('ENGINE')
NAME=os.environ.get('NAME')
PASSWORD=os.environ.get('PASSWORD')
PORT=os.environ.get('PORT')

if isLocal=='True':
    USER=os.environ.get('USER_LOCAL')
    HOST=os.environ.get('HOST_LOCAL')

if isDocker=='True':
    USER=os.environ.get('USER_DOCKER')
    HOST=os.environ.get('HOST_DOCKER')

if isAWS=='True':
    USER=os.environ.get('USER_AWS')
    HOST=os.environ.get('HOST_AWS')

DATABASES = {
    'default': {
        'ENGINE':ENGINE,
        'NAME':NAME,
        'USER':USER,
        'PASSWORD':PASSWORD,
        'HOST':HOST,
        'PORT':PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = os.environ.get('ALLOWED_ORIGINS').split()
DATA_UPLOAD_MAX_MEMORY_SIZE = 8388608 

